<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataContracts\Album\**" />
    <Compile Remove="DataContracts\Artist\**" />
    <EmbeddedResource Remove="DataContracts\Album\**" />
    <EmbeddedResource Remove="DataContracts\Artist\**" />
    <None Remove="DataContracts\Album\**" />
    <None Remove="DataContracts\Artist\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataContracts\Common\" />
  </ItemGroup>

</Project>
