<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<PackageId>Jukebox.DataAccess.EntityFramework</PackageId>
		<Authors>jonwong84</Authors>
		<Description>EF Core DbContext and entity models for the Jukebox API.</Description>
		<RepositoryUrl>https://github.com/jonwong84/jukebox-data-access</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.27" />
	</ItemGroup>

</Project>